/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as CollectionsRouteImport } from './routes/collections'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as MarbleRouteImport } from './routes/marble'
import { Route as PartnersRouteImport } from './routes/partners'
import { Route as ShowroomRouteImport } from './routes/showroom'
import { Route as SpacesRouteImport } from './routes/spaces'
import { Route as TestimonialsRouteImport } from './routes/testimonials'
import { Route as TilesRouteImport } from './routes/tiles'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsRoute = CollectionsRouteImport.update({
  id: '/collections',
  path: '/collections',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const MarbleRoute = MarbleRouteImport.update({
  id: '/marble',
  path: '/marble',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnersRoute = PartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => rootRouteImport,
} as any)
const ShowroomRoute = ShowroomRouteImport.update({
  id: '/showroom',
  path: '/showroom',
  getParentRoute: () => rootRouteImport,
} as any)
const SpacesRoute = SpacesRouteImport.update({
  id: '/spaces',
  path: '/spaces',
  getParentRoute: () => rootRouteImport,
} as any)
const TestimonialsRoute = TestimonialsRouteImport.update({
  id: '/testimonials',
  path: '/testimonials',
  getParentRoute: () => rootRouteImport,
} as any)
const TilesRoute = TilesRouteImport.update({
  id: '/tiles',
  path: '/tiles',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/collections': typeof CollectionsRoute
  '/contact': typeof ContactRoute
  '/marble': typeof MarbleRoute
  '/partners': typeof PartnersRoute
  '/showroom': typeof ShowroomRoute
  '/spaces': typeof SpacesRoute
  '/testimonials': typeof TestimonialsRoute
  '/tiles': typeof TilesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/collections': typeof CollectionsRoute
  '/contact': typeof ContactRoute
  '/marble': typeof MarbleRoute
  '/partners': typeof PartnersRoute
  '/showroom': typeof ShowroomRoute
  '/spaces': typeof SpacesRoute
  '/testimonials': typeof TestimonialsRoute
  '/tiles': typeof TilesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/collections': typeof CollectionsRoute
  '/contact': typeof ContactRoute
  '/marble': typeof MarbleRoute
  '/partners': typeof PartnersRoute
  '/showroom': typeof ShowroomRoute
  '/spaces': typeof SpacesRoute
  '/testimonials': typeof TestimonialsRoute
  '/tiles': typeof TilesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/collections'
    | '/contact'
    | '/marble'
    | '/partners'
    | '/showroom'
    | '/spaces'
    | '/testimonials'
    | '/tiles'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/collections'
    | '/contact'
    | '/marble'
    | '/partners'
    | '/showroom'
    | '/spaces'
    | '/testimonials'
    | '/tiles'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/collections'
    | '/contact'
    | '/marble'
    | '/partners'
    | '/showroom'
    | '/spaces'
    | '/testimonials'
    | '/tiles'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CollectionsRoute: typeof CollectionsRoute
  ContactRoute: typeof ContactRoute
  MarbleRoute: typeof MarbleRoute
  PartnersRoute: typeof PartnersRoute
  ShowroomRoute: typeof ShowroomRoute
  SpacesRoute: typeof SpacesRoute
  TestimonialsRoute: typeof TestimonialsRoute
  TilesRoute: typeof TilesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections': {
      id: '/collections'
      path: '/collections'
      fullPath: '/collections'
      preLoaderRoute: typeof CollectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marble': {
      id: '/marble'
      path: '/marble'
      fullPath: '/marble'
      preLoaderRoute: typeof MarbleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partners': {
      id: '/partners'
      path: '/partners'
      fullPath: '/partners'
      preLoaderRoute: typeof PartnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/showroom': {
      id: '/showroom'
      path: '/showroom'
      fullPath: '/showroom'
      preLoaderRoute: typeof ShowroomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spaces': {
      id: '/spaces'
      path: '/spaces'
      fullPath: '/spaces'
      preLoaderRoute: typeof SpacesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/testimonials': {
      id: '/testimonials'
      path: '/testimonials'
      fullPath: '/testimonials'
      preLoaderRoute: typeof TestimonialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tiles': {
      id: '/tiles'
      path: '/tiles'
      fullPath: '/tiles'
      preLoaderRoute: typeof TilesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CollectionsRoute: CollectionsRoute,
  ContactRoute: ContactRoute,
  MarbleRoute: MarbleRoute,
  PartnersRoute: PartnersRoute,
  ShowroomRoute: ShowroomRoute,
  SpacesRoute: SpacesRoute,
  TestimonialsRoute: TestimonialsRoute,
  TilesRoute: TilesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
